# Generated by Django 5.1.6 on 2025-05-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_classmate_educationalprogram_management_pagecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Имя и Фамилия')),
                ('educational_program', models.CharField(max_length=100, verbose_name='Образовательная программа')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['full_name', 'course'],
            },
        ),
    ]
